apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
spec:
  action: pod-kill
  mode: one
  duration: "30s"
  selector:
    labelSelectors:
      "app.kubernetes.io/managed-by": "cassandra-operator"
  scheduler:
    cron: "@every 5m"
